// scripts/deploy-hardhat.js
const hre = require("hardhat");
const {
  Client,
  AccountId,
  PrivateKey,
  TopicCreateTransaction,
} = require("@hashgraph/sdk");
require("dotenv").config();

async function createHCSTopics() {
  const accountId = AccountId.fromString(process.env.HEDERA_ACCOUNT_ID);
  const privateKey = PrivateKey.fromStringECDSA(process.env.HEDERA_PRIVATE_KEY);
  const client = hre.network.name === "hederaTestnet"
    ? (() => { const c = Client.forTestnet(); c.setOperator(accountId, privateKey); return c; })()
    : (() => { const c = Client.forMainnet(); c.setOperator(accountId, privateKey); return c; })();

  console.log("\n📝 Creating HCS topics for demo farms...");
  const topicIds = [];

  for (let i = 0; i < 3; i++) {
    const tx = await new TopicCreateTransaction()
      .setTopicMemo(`RainSafe Farm #${i} Climate Events`)
      .execute(client);
    const receipt = await tx.getReceipt(client);
    topicIds.push(receipt.topicId.toString());
    console.log(`  ✅ Farm #${i} HCS topic: ${receipt.topicId}`);
  }

  return topicIds;
}

async function main() {
  console.log(`\n🌐 Deploying RainSafe to ${hre.network.name}...`);

  const RainSafe = await hre.ethers.getContractFactory("RainSafe");
  console.log("🔨 Compiling and deploying...");

  const contract = await RainSafe.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log(`✅ RainSafe deployed at: ${address}`);
  console.log(`🔍 View on HashScan: https://hashscan.io/testnet/contract/${address}`);

  // Create HCS topics
  const topicIds = await createHCSTopics();

  // Save to .env
  const fs = require("fs");
  const path = require("path");
  const envPath = path.join(__dirname, "../.env");
  const additions = `
# Generated by deploy-hardhat.js
CONTRACT_ADDRESS=${address}
HCS_TOPIC_FARM_0=${topicIds[0]}
HCS_TOPIC_FARM_1=${topicIds[1]}
HCS_TOPIC_FARM_2=${topicIds[2]}
`;
  fs.appendFileSync(envPath, additions);
  console.log("\n✅ Contract address and HCS topics saved to .env");
  console.log("\n🚀 Deployment complete!");
  console.log(`   Contract: ${address}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
